export const routes = {
  splash: 'Splash',
  login: 'Login',
  signup: 'Signup',
  otp: 'Otp',
  kyc: 'Kyc',
  reset: 'ResetPassword',
  dashboard: 'Dashboard',
  explore: 'Explore',
  groupDetail: 'GroupDetail',
  createBasics: 'CreateGroupBasics',
  createRules: 'CreateGroupRules',
  groupStatus: 'GroupStatus',
  payment: 'Payment',
  mockUssd: 'MockUssd',
  paymentSuccess: 'PaymentSuccess',
  history: 'History',
  wallet: 'Wallet',
  withdraw: 'Withdraw',
  notifications: 'Notifications',
  profile: 'Profile',
  adminDashboard: 'AdminDashboard',
  adminKyc: 'AdminKyc',
  adminGroups: 'AdminGroups',
  adminReports: 'AdminReports',
} as const;
