import { StyleSheet } from 'react-native';
import { palette, radii, shadows, spacing } from '../../theme/tokens';

export const adminStyles = StyleSheet.create({
  twoCol: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  listGroup: {
    gap: spacing.xs,
  },
  sectionTitle: {
    color: palette.text,
    fontWeight: '800',
    fontSize: 18,
  },
  mutedText: {
    color: palette.textMuted,
    lineHeight: 20,
  },
  actionGroup: {
    gap: spacing.xs,
  },
  adminEyebrow: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  kycQueueHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingTop: spacing.xs,
  },
  kycQueueHeaderText: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xs,
  },
  kycQueueTitle: {
    color: palette.text,
    fontSize: 31,
    lineHeight: 37,
    fontWeight: '900',
  },
  kycQueueSubtitle: {
    maxWidth: 330,
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
  },
  kycQueuePendingPill: {
    minHeight: 36,
    justifyContent: 'center',
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    backgroundColor: palette.primarySoft,
  },
  kycQueuePendingText: {
    color: palette.primary,
    fontSize: 13,
    fontWeight: '900',
  },
  kycSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  kycSearchBox: {
    flex: 1,
    minHeight: 54,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  kycSearchInput: {
    flex: 1,
    color: palette.text,
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: spacing.sm,
  },
  kycFilterButton: {
    minWidth: 86,
    minHeight: 54,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  kycFilterText: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: '900',
  },
  kycQueueTabs: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'stretch',
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    padding: spacing.xs,
    ...shadows.card,
  },
  kycQueueTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.md,
    borderRightWidth: 1,
    borderRightColor: palette.border,
    gap: spacing.xxs,
    paddingHorizontal: spacing.xxs,
  },
  kycQueueTabActive: {
    borderWidth: 1,
    borderColor: palette.primary,
    backgroundColor: '#F3F8FF',
  },
  kycQueueTabLabel: {
    color: palette.textMuted,
    fontSize: 10,
    fontWeight: '900',
    textAlign: 'center',
  },
  kycQueueTabLabelActive: {
    color: palette.primary,
  },
  kycQueueTabCount: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: '900',
  },
  kycQueueTabCountActive: {
    color: palette.primary,
  },
  kycQueueList: {
    gap: spacing.sm,
  },
  kycQueueCard: {
    minHeight: 94,
    borderRadius: radii.lg,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    ...shadows.card,
  },
  kycQueueAvatar: {
    width: 56,
    height: 56,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
  },
  kycQueueCardText: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xxs,
  },
  kycQueueName: {
    color: palette.text,
    fontSize: 16,
    fontWeight: '900',
  },
  kycQueueMeta: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  kycQueueNoteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  kycQueueNoteDot: {
    width: 5,
    height: 5,
    borderRadius: radii.pill,
    backgroundColor: palette.warning,
  },
  kycQueueNote: {
    flex: 1,
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  kycReviewProfileCard: {
    borderRadius: radii.lg,
    padding: spacing.lg,
    gap: spacing.md,
  },
  kycReviewProfileTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  kycReviewAvatar: {
    width: 72,
    height: 72,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
  },
  kycReviewProfileText: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xs,
  },
  kycReviewName: {
    color: palette.text,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '900',
  },
  kycReviewPhone: {
    color: palette.textMuted,
    fontSize: 15,
    fontWeight: '700',
  },
  kycReviewDivider: {
    height: 1,
    backgroundColor: palette.border,
  },
  kycReviewNoteRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  kycReviewNoteIcon: {
    width: 44,
    height: 44,
    borderRadius: radii.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
  },
  kycReviewNoteText: {
    flex: 1,
    minWidth: 0,
  },
  kycReviewNoteTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: '900',
  },
  kycReviewNoteBody: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: spacing.xxs,
  },
  kycReviewDocumentsCard: {
    borderRadius: radii.lg,
    padding: spacing.md,
    gap: spacing.md,
  },
  kycReviewSectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  kycReviewSectionTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '900',
  },
  kycReviewSectionBody: {
    maxWidth: 270,
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: spacing.xs,
  },
  kycReviewDocumentCount: {
    color: palette.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  kycDocumentRow: {
    minHeight: 78,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.backgroundSoft,
    padding: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  kycDocumentIcon: {
    width: 46,
    height: 46,
    borderRadius: radii.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
  },
  kycDocumentText: {
    flex: 1,
    minWidth: 0,
  },
  kycDocumentTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: '900',
    textTransform: 'capitalize',
  },
  kycDocumentSubtitle: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  kycDocumentMeta: {
    color: palette.textSoft,
    fontSize: 11,
    marginTop: 2,
  },
  kycDocumentDownload: {
    width: 36,
    height: 36,
    borderRadius: radii.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  kycChecklistCard: {
    borderRadius: radii.md,
    padding: spacing.md,
    gap: spacing.sm,
    backgroundColor: '#EEF6FF',
    borderColor: '#BFD6FC',
  },
  kycChecklistHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  kycChecklistHeading: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '900',
  },
  kycChecklistGrid: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  kycChecklistItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xs,
  },
  kycChecklistIcon: {
    width: 22,
    height: 22,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.success,
  },
  kycChecklistText: {
    flex: 1,
    minWidth: 0,
  },
  kycChecklistTitle: {
    color: palette.text,
    fontSize: 11,
    fontWeight: '900',
  },
  kycChecklistBody: {
    color: palette.textMuted,
    fontSize: 10,
    lineHeight: 14,
    marginTop: 1,
  },
  kycDecisionButton: {
    minHeight: 56,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.primary,
    backgroundColor: palette.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  kycDecisionButtonPrimary: {
    backgroundColor: palette.primary,
    ...shadows.card,
  },
  kycDecisionButtonDanger: {
    borderColor: '#F5B8B3',
    backgroundColor: '#FFF7F7',
  },
  kycDecisionButtonDisabled: {
    opacity: 0.55,
  },
  kycDecisionButtonText: {
    color: palette.primary,
    fontSize: 15,
    fontWeight: '900',
  },
  kycDecisionButtonTextPrimary: {
    color: palette.white,
  },
  kycDecisionButtonTextDanger: {
    color: palette.danger,
  },
});
