import { StyleSheet } from 'react-native';
import { palette, radii, spacing } from '../../theme/tokens';

export const authStyles = StyleSheet.create({
  centeredContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: spacing.sm,
  },
  stack: {
    gap: spacing.md,
  },
  heroImageWrap: {
    height: 204,
    borderRadius: radii.xl,
    overflow: 'hidden',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  brandMark: {
    width: 60,
    height: 60,
    borderRadius: radii.xl,
    backgroundColor: palette.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandLetter: {
    color: palette.primaryDark,
    fontSize: 24,
    fontWeight: '800',
  },
  centered: {
    alignItems: 'center',
  },
  mutedText: {
    color: palette.textMuted,
  },
  strongText: {
    color: palette.text,
    fontWeight: '700',
  },
  helperBlock: {
    gap: spacing.xs,
  },
  fieldGroup: {
    gap: spacing.sm,
  },
  buttonGroup: {
    gap: spacing.sm,
  },
  kycCard: {
    gap: spacing.sm,
  },
  kycDocHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
  },
  kycActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  progressTrack: {
    height: 10,
    borderRadius: radii.pill,
    backgroundColor: '#DFE7F0',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: palette.primary,
  },
  heroActions: {
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  demoHeroEyebrow: {
    color: palette.accentSoft,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  demoHeroTitle: {
    color: palette.white,
    fontSize: 25,
    fontWeight: '800',
    lineHeight: 31,
  },
  demoHeroBody: {
    color: '#DDEBFF',
    lineHeight: 21,
  },
  demoList: {
    gap: spacing.xs,
  },
  segmentedWrap: {
    gap: spacing.xs,
  },
  footerActions: {
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  signupScreen: {
    flex: 1,
    justifyContent: 'flex-start',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  signupProgressWrap: {
    gap: spacing.xxs,
  },
  signupProgressTrack: {
    height: 7,
    borderRadius: radii.pill,
    backgroundColor: '#D9E4F2',
    overflow: 'hidden',
  },
  signupProgressFill: {
    height: '100%',
    borderRadius: radii.pill,
    backgroundColor: palette.primary,
  },
  signupProgressText: {
    color: palette.primary,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  signupTitleWrap: {
    gap: spacing.xxs,
  },
  signupTitle: {
    color: palette.text,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '900',
  },
  signupSubtitle: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  loginScreen: {
    flex: 1,
    justifyContent: 'flex-start',
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
  },
  loginHeader: {
    alignItems: 'center',
    gap: spacing.xs,
  },
  loginTitle: {
    color: palette.text,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '900',
    textAlign: 'center',
  },
  loginSubtitle: {
    maxWidth: 280,
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    fontWeight: '600',
  },
  loginRoleSwitch: {
    flexDirection: 'row',
    alignSelf: 'center',
    width: '84%',
    minHeight: 52,
    borderRadius: radii.pill,
    padding: spacing.xxs,
    backgroundColor: '#F5F9FF',
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
    elevation: 3,
  },
  loginRoleButton: {
    flex: 1,
    borderRadius: radii.pill,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  loginRoleButtonActive: {
    backgroundColor: palette.white,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 2,
  },
  loginRoleButtonText: {
    color: palette.textMuted,
    fontSize: 16,
    fontWeight: '800',
  },
  loginRoleButtonTextActive: {
    color: palette.primary,
  },
  loginFormCard: {
    minHeight: 232,
    borderRadius: radii.xl,
    backgroundColor: palette.surface,
    padding: spacing.lg,
    paddingBottom: spacing.xl,
    gap: spacing.lg,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 22,
    elevation: 4,
    overflow: 'visible',
  },
  loginFieldGroup: {
    gap: spacing.xs,
  },
  loginFieldLabel: {
    color: palette.text,
    fontSize: 15,
    fontWeight: '900',
  },
  loginPhoneRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  loginCountryBox: {
    minWidth: 110,
    minHeight: 52,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    backgroundColor: palette.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
  },
  loginFlag: {
    fontSize: 20,
  },
  loginCountryCode: {
    color: palette.text,
    fontSize: 16,
    fontWeight: '900',
  },
  loginInputWrap: {
    flex: 1,
    minHeight: 52,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    backgroundColor: palette.surface,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  loginInput: {
    flex: 1,
    color: palette.text,
    fontSize: 16,
    fontWeight: '700',
    paddingVertical: spacing.sm,
  },
  loginEyeButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
  },
  loginSecurityBox: {
    minHeight: 74,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#BED3F7',
    backgroundColor: '#EFF6FF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
  },
  loginSecurityIcon: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    backgroundColor: palette.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginSecurityText: {
    flex: 1,
    minWidth: 0,
  },
  loginSecurityTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: '900',
  },
  loginSecurityBody: {
    color: palette.text,
    fontSize: 13,
    lineHeight: 19,
    marginTop: spacing.xxs,
  },
  loginActions: {
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  loginPrimaryButton: {
    minHeight: 52,
    borderRadius: radii.md,
    backgroundColor: palette.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    shadowColor: palette.primary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.23,
    shadowRadius: 18,
    elevation: 5,
  },
  loginButtonDisabled: {
    opacity: 0.56,
  },
  loginPrimaryButtonText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
  },
  loginSecondaryButton: {
    minHeight: 50,
    borderRadius: radii.md,
    backgroundColor: palette.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  loginSecondaryButtonText: {
    color: palette.primary,
    fontSize: 15,
    fontWeight: '900',
  },
  savedAccountDropdown: {
    gap: spacing.xs,
    marginTop: spacing.md,
  },
  savedAccountOption: {
    minHeight: 44,
    borderRadius: radii.md,
    backgroundColor: '#F4F8FF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: palette.border,
  },
  loginFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.xl,
    marginTop: spacing.xs,
  },
  loginFooterText: {
    flexShrink: 1,
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
    textAlign: 'center',
  },
});
