import { StyleSheet } from 'react-native';
import { palette, radii, shadows, spacing } from '../../theme/tokens';

export const memberStyles = StyleSheet.create({
  sectionGap: {
    gap: spacing.sm,
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
  },
  itemBlock: {
    gap: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: palette.border,
  },
  twoCol: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    alignItems: 'stretch',
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  dashboardHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    minHeight: 40,
  },
  profileIconButton: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    ...shadows.subtle,
  },
  profileDetailsPanel: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  profileName: {
    color: palette.text,
    fontWeight: '800',
    fontSize: 16,
  },
  profileMeta: {
    color: palette.textMuted,
    marginTop: spacing.xxs,
  },
  profileStatusPill: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: palette.successSurface,
  },
  profileStatusText: {
    color: palette.success,
    fontWeight: '800',
    fontSize: 12,
  },
  dashboardHeroCard: {
    overflow: 'hidden',
    borderRadius: radii.xl,
    backgroundColor: '#075CD7',
    padding: spacing.lg,
    gap: spacing.md,
    ...shadows.hero,
  },
  dashboardHeroArt: {
    position: 'absolute',
    top: 76,
    right: 14,
    width: 112,
    height: 118,
    opacity: 0.44,
  },
  dashboardVaultBody: {
    position: 'absolute',
    top: 8,
    right: 0,
    width: 84,
    height: 84,
    borderRadius: radii.lg,
    backgroundColor: '#7DB6FF',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.36)',
    transform: [{ rotate: '-8deg' }],
  },
  dashboardVaultDoor: {
    position: 'absolute',
    top: 14,
    left: 12,
    right: 12,
    bottom: 14,
    borderRadius: radii.md,
    borderWidth: 2,
    borderColor: '#075CD7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardVaultDial: {
    width: 18,
    height: 18,
    borderRadius: radii.pill,
    borderWidth: 4,
    borderColor: '#2F80EA',
  },
  dashboardCoinStack: {
    position: 'absolute',
    bottom: 6,
    left: 4,
    width: 68,
    height: 44,
  },
  dashboardCoin: {
    position: 'absolute',
    right: 0,
    bottom: 16,
    width: 42,
    height: 18,
    borderRadius: radii.pill,
    backgroundColor: '#9AC5FF',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.48)',
  },
  dashboardCoinOffset: {
    right: 18,
    bottom: 4,
    width: 34,
  },
  dashboardCoinLower: {
    right: 30,
    bottom: 22,
    width: 30,
  },
  dashboardHeroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  dashboardHeroPill: {
    flex: 1,
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    backgroundColor: 'rgba(255,255,255,0.13)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  dashboardHeroPillText: {
    flex: 1,
    color: palette.white,
    fontWeight: '700',
  },
  dashboardRoundPill: {
    minHeight: 36,
    justifyContent: 'center',
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    backgroundColor: 'rgba(11,51,125,0.62)',
  },
  dashboardRoundText: {
    color: palette.white,
    fontWeight: '800',
  },
  dashboardHeroAmount: {
    color: palette.white,
    fontSize: 42,
    fontWeight: '900',
    lineHeight: 50,
    maxWidth: '68%',
  },
  dashboardHeroBody: {
    color: 'rgba(255,255,255,0.88)',
    fontSize: 15,
    lineHeight: 23,
    maxWidth: '72%',
  },
  dashboardHeroBodyStrong: {
    color: '#FFE08A',
    fontWeight: '900',
  },
  heroPayButton: {
    minHeight: 58,
    borderRadius: radii.lg,
    backgroundColor: palette.white,
    paddingHorizontal: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    ...shadows.card,
  },
  heroPayButtonText: {
    color: palette.primary,
    fontSize: 18,
    fontWeight: '900',
  },
  dashboardHeroDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  dashboardHeroDetailRow: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  dashboardHeroIcon: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
  },
  dashboardHeroDetailText: {
    flex: 1,
    gap: spacing.xxs,
  },
  dashboardHeroDetailTitle: {
    color: palette.white,
    fontWeight: '900',
    fontSize: 15,
  },
  dashboardHeroDetailBody: {
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 19,
  },
  dashboardProgressPill: {
    minWidth: 52,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(11,51,125,0.38)',
  },
  dashboardProgressText: {
    color: palette.white,
    fontWeight: '800',
  },
  dashboardMiniMetrics: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  dashboardPanel: {
    borderRadius: radii.lg,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  dashboardSectionTitle: {
    color: palette.text,
    fontWeight: '900',
    fontSize: 15,
  },
  quickActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  quickActionTile: {
    flexBasis: '48.5%',
    flexGrow: 1,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.sm,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
    backgroundColor: palette.primarySoft,
    borderWidth: 1,
    borderColor: '#A8C8F7',
  },
  quickActionIcon: {
    width: 28,
    height: 28,
    borderRadius: radii.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: '#C8DBFA',
  },
  quickActionText: {
    flex: 1,
    color: palette.text,
    fontWeight: '900',
    fontSize: 12,
  },
  recentActivityRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  recentActivityIcon: {
    width: 30,
    height: 30,
    borderRadius: radii.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
  },
  recentActivityText: {
    flex: 1,
    minWidth: 0,
  },
  recentActivityTitle: {
    color: palette.text,
    fontWeight: '900',
    fontSize: 13,
  },
  recentActivityMeta: {
    color: palette.textMuted,
    fontSize: 11,
    marginTop: 2,
  },
  recentActivityDate: {
    color: palette.textSoft,
    fontSize: 11,
  },
  exploreTitle: {
    color: palette.text,
    fontSize: 32,
    fontWeight: '900',
    lineHeight: 40,
  },
  exploreHeroCard: {
    overflow: 'hidden',
    borderRadius: radii.xl,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.lg,
    minHeight: 204,
    gap: spacing.sm,
    ...shadows.card,
  },
  exploreHeroArt: {
    position: 'absolute',
    top: 0,
    right: -4,
    width: 170,
    height: 170,
    opacity: 0.58,
  },
  exploreVaultBody: {
    position: 'absolute',
    top: 50,
    right: 14,
    width: 92,
    height: 92,
    borderRadius: radii.lg,
    backgroundColor: '#86BAFF',
    borderWidth: 2,
    borderColor: '#BFD9FF',
    transform: [{ rotate: '-8deg' }],
  },
  exploreVaultDoor: {
    position: 'absolute',
    top: 15,
    left: 13,
    right: 13,
    bottom: 15,
    borderRadius: radii.md,
    borderWidth: 2,
    borderColor: palette.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exploreVaultDial: {
    width: 19,
    height: 19,
    borderRadius: radii.pill,
    borderWidth: 4,
    borderColor: '#3C86EA',
  },
  exploreCoinStack: {
    position: 'absolute',
    right: 68,
    bottom: 8,
    width: 72,
    height: 52,
  },
  exploreCoin: {
    position: 'absolute',
    right: 0,
    bottom: 18,
    width: 44,
    height: 18,
    borderRadius: radii.pill,
    backgroundColor: '#9AC5FF',
    borderWidth: 1,
    borderColor: '#D4E6FF',
  },
  exploreCoinOffset: {
    right: 18,
    bottom: 5,
    width: 36,
  },
  exploreCoinLower: {
    right: 30,
    bottom: 28,
    width: 30,
  },
  exploreHeroIcon: {
    width: 44,
    height: 44,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
  },
  exploreHeroTitle: {
    maxWidth: '72%',
    color: palette.text,
    fontWeight: '900',
    fontSize: 24,
    lineHeight: 30,
  },
  exploreHeroBody: {
    maxWidth: '60%',
    color: palette.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  exploreHeroActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  explorePrimaryAction: {
    flex: 1,
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    borderRadius: radii.md,
    backgroundColor: palette.primary,
    ...shadows.subtle,
  },
  explorePrimaryActionText: {
    color: palette.white,
    fontWeight: '900',
    fontSize: 15,
  },
  exploreSecondaryAction: {
    flex: 1,
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    borderRadius: radii.md,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.primary,
  },
  exploreSecondaryActionText: {
    color: palette.primary,
    fontWeight: '900',
    fontSize: 15,
  },
  exploreRequestsCard: {
    minHeight: 96,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.xl,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.lg,
    ...shadows.card,
  },
  exploreRequestsIcon: {
    width: 48,
    height: 48,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
  },
  exploreRequestsText: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xxs,
  },
  exploreRequestsTitle: {
    color: palette.text,
    fontWeight: '900',
    fontSize: 19,
  },
  exploreRequestsBody: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  exploreCountPill: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: palette.primarySoft,
  },
  exploreCountText: {
    color: palette.primary,
    fontWeight: '900',
    fontSize: 12,
  },
  exploreFormingPanel: {
    padding: 0,
    overflow: 'hidden',
    gap: 0,
  },
  exploreSectionTitle: {
    color: palette.text,
    fontWeight: '900',
    fontSize: 21,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  exploreSectionHeading: {
    color: palette.text,
    fontWeight: '900',
    fontSize: 22,
    marginTop: spacing.xs,
  },
  exploreEmptyState: {
    minHeight: 188,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    padding: spacing.lg,
  },
  exploreEmptyCard: {
    minHeight: 188,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    borderRadius: radii.xl,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.lg,
    ...shadows.card,
  },
  exploreEmptyIcon: {
    width: 66,
    height: 66,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
    borderWidth: 1,
    borderColor: palette.border,
  },
  exploreEmptyTitle: {
    color: palette.text,
    fontWeight: '900',
    fontSize: 20,
    textAlign: 'center',
  },
  exploreEmptyBody: {
    maxWidth: 280,
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  exploreCardList: {
    gap: spacing.sm,
  },
  exploreSmallPill: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    borderRadius: radii.sm,
    paddingHorizontal: spacing.xs,
    backgroundColor: palette.primarySoft,
    borderWidth: 1,
    borderColor: '#BFD6FC',
  },
  exploreSmallPillSuccess: {
    backgroundColor: palette.successSurface,
    borderColor: '#BDE8D0',
  },
  exploreSmallPillText: {
    color: palette.primary,
    fontWeight: '800',
    fontSize: 12,
  },
  exploreSmallPillTextSuccess: {
    color: palette.success,
  },
  formingRequestCard: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.md,
    gap: spacing.sm,
    borderRadius: radii.lg,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.md,
  },
  approvedGroupCard: {
    gap: spacing.sm,
    borderRadius: radii.xl,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.md,
    ...shadows.card,
  },
  approvedGroupTitle: {
    color: palette.text,
    fontWeight: '900',
    fontSize: 21,
    lineHeight: 27,
  },
  approvedGroupDescription: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  approvedStatsBox: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.backgroundSoft,
    padding: spacing.sm,
  },
  approvedStatItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minWidth: 0,
  },
  approvedStatIcon: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
  },
  approvedStatLabel: {
    color: palette.textSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  approvedStatValue: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 2,
  },
  approvedStatHelper: {
    color: palette.textMuted,
    fontSize: 10,
    marginTop: 2,
  },
  approvedStatDivider: {
    width: 1,
    height: 42,
    backgroundColor: palette.border,
  },
  approvedGroupButton: {
    minHeight: 48,
    borderRadius: radii.md,
    backgroundColor: palette.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
  },
  approvedGroupButtonText: {
    color: palette.white,
    fontWeight: '900',
    fontSize: 15,
  },
  groupStatusHeader: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  groupStatusBack: {
    width: 46,
    height: 46,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    ...shadows.subtle,
  },
  groupStatusTitle: {
    flex: 1,
    color: palette.text,
    fontWeight: '900',
    fontSize: 22,
    lineHeight: 26,
  },
  groupStatusPill: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: palette.primarySoft,
  },
  groupStatusPillText: {
    color: palette.primary,
    fontWeight: '800',
    fontSize: 12,
  },
  ringCard: {
    borderRadius: radii.xl,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.md,
    gap: spacing.md,
    ...shadows.card,
  },
  ringTopPillBlue: {
    minHeight: 28,
    justifyContent: 'center',
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    backgroundColor: palette.primarySoft,
  },
  ringTopPillBlueText: {
    color: palette.primary,
    fontWeight: '800',
    fontSize: 12,
  },
  ringTopPillAmber: {
    minHeight: 28,
    justifyContent: 'center',
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    backgroundColor: palette.warningSurface,
  },
  ringTopPillAmberText: {
    color: palette.warning,
    fontWeight: '800',
    fontSize: 12,
  },
  ringCanvas: {
    width: 304,
    height: 304,
    alignSelf: 'center',
    overflow: 'visible',
  },
  ringOuter: {
    position: 'absolute',
    borderRadius: radii.pill,
    backgroundColor: '#9AA1AA',
    borderWidth: 1,
    borderColor: '#C4CAD3',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
    elevation: 2,
  },
  ringInner: {
    position: 'absolute',
    borderRadius: radii.pill,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  ringCounter: {
    position: 'absolute',
    left: 81,
    top: 112,
    width: 142,
    alignItems: 'center',
  },
  ringCounterTitle: {
    color: palette.text,
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  ringCounterSubtitle: {
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
  ringReadyLabel: {
    color: palette.primary,
    fontSize: 10,
    fontWeight: '900',
    marginTop: spacing.xs,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xxs,
    borderRadius: radii.pill,
    backgroundColor: palette.primarySoft,
    overflow: 'hidden',
  },
  ringPillButton: {
    position: 'absolute',
    left: 0,
    top: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  ringPillButtonRaised: {
    zIndex: 6,
  },
  ringPillShell: {
    borderRadius: radii.pill,
    backgroundColor: '#E2E8F0',
    borderColor: '#CBD5E1',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.14,
    shadowRadius: 7,
    elevation: 2,
  },
  ringPillShellPaid: {
    backgroundColor: palette.primary,
    borderColor: '#DBEAFE',
  },
  ringPillShellWinner: {
    backgroundColor: '#E7B63D',
    borderColor: '#C98500',
  },
  ringPillSelected: {
    shadowColor: palette.primary,
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 4,
  },
  ringPillInner: {
    flex: 1,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  ringPillInnerPaid: {
    backgroundColor: 'rgba(147,197,253,0.85)',
  },
  ringPillInnerWinner: {
    backgroundColor: '#FFF8D9',
  },
  ringNote: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.xl,
  },
  ringNoteText: {
    flex: 1,
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  ringWinnerSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(231,182,61,0.52)',
    backgroundColor: '#FFF8E1',
    padding: spacing.sm,
  },
  ringWinnerIcon: {
    width: 44,
    height: 44,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E7B63D',
    borderWidth: 1,
    borderColor: 'rgba(201,133,0,0.30)',
  },
  ringWinnerText: {
    flex: 1,
    minWidth: 0,
  },
  ringWinnerEyebrow: {
    color: '#9A6A00',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  ringWinnerName: {
    color: '#4A2A00',
    fontSize: 15,
    fontWeight: '900',
    marginTop: 2,
  },
  ringWinnerMeta: {
    color: '#7A4A00',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  ringProfile: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceAlt,
    padding: spacing.sm,
  },
  ringProfileAvatar: {
    width: 44,
    height: 44,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  ringProfileInitials: {
    color: palette.text,
    fontSize: 12,
    fontWeight: '900',
  },
  ringProfileBody: {
    flex: 1,
    minWidth: 0,
    gap: spacing.sm,
  },
  ringProfileNameWrap: {
    flex: 1,
    minWidth: 0,
  },
  ringProfileName: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '900',
  },
  ringProfileMeta: {
    color: palette.textMuted,
    fontSize: 10,
    fontWeight: '700',
    marginTop: 2,
  },
  ringProfileClose: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  ringProfileStats: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  ringProfileStat: {
    flex: 1,
    minHeight: 56,
    justifyContent: 'center',
    borderRadius: radii.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.xs,
  },
  ringProfileStatLabel: {
    color: palette.textSoft,
    fontSize: 9,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  ringProfileStatValue: {
    color: palette.text,
    fontSize: 10,
    fontWeight: '900',
    marginTop: spacing.xs,
  },
  ringProfileState: {
    alignSelf: 'flex-start',
    overflow: 'hidden',
    color: palette.textMuted,
    fontSize: 9,
    fontWeight: '900',
    marginTop: spacing.xs,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    backgroundColor: palette.surfaceSoft,
  },
  ringProfileStatePaid: {
    color: palette.primary,
    backgroundColor: palette.primarySoft,
  },
  ringProfileStateWinner: {
    color: '#7A4A00',
    backgroundColor: '#FFF3C2',
  },
  ringOverflowNote: {
    color: palette.warning,
    fontSize: 11,
    fontWeight: '700',
    borderRadius: radii.md,
    backgroundColor: palette.warningSurface,
    padding: spacing.sm,
  },
  winnerHistoryCard: {
    gap: spacing.sm,
  },
  winnerHistoryTitle: {
    color: palette.text,
    fontWeight: '900',
    fontSize: 17,
  },
  winnerHistoryList: {
    gap: spacing.xs,
  },
  winnerHistoryRow: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  winnerHistoryIcon: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
  },
  winnerHistoryText: {
    flex: 1,
    minWidth: 0,
  },
  winnerHistoryRound: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '900',
  },
  winnerHistoryName: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  miniMetricCard: {
    flex: 1,
    minHeight: 78,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    ...shadows.subtle,
  },
  miniMetricIcon: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primarySoft,
  },
  miniMetricIconActive: {
    backgroundColor: palette.successSurface,
  },
  miniMetricText: {
    flex: 1,
    minWidth: 0,
  },
  miniMetricLabel: {
    color: palette.textSoft,
    fontWeight: '900',
    fontSize: 11,
    textTransform: 'uppercase',
  },
  miniMetricValue: {
    color: palette.text,
    fontWeight: '900',
    fontSize: 16,
    marginTop: spacing.xxs,
  },
  miniMetricHelper: {
    color: palette.textMuted,
    fontSize: 11,
    marginTop: 2,
  },
  imageHeroWrap: {
    height: 164,
    borderRadius: radii.xl,
    overflow: 'hidden',
  },
  imageHero: {
    width: '100%',
    height: '100%',
  },
  sectionTitle: {
    color: palette.text,
    fontWeight: '800',
    fontSize: 18,
  },
  mutedText: {
    color: palette.textMuted,
    lineHeight: 20,
  },
  strongText: {
    color: palette.text,
    fontWeight: '700',
  },
  heroValue: {
    color: palette.white,
    fontSize: 30,
    fontWeight: '900',
    marginTop: spacing.xs,
  },
  heroBody: {
    color: 'rgba(255,255,255,0.84)',
    marginTop: spacing.xs,
    lineHeight: 21,
  },
  actionGroup: {
    gap: spacing.xs,
  },
  inviteActions: {
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  iconAction: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.border,
  },
  listGroup: {
    gap: spacing.xs,
  },
  amountPositive: {
    color: palette.success,
    fontWeight: '800',
    fontSize: 20,
  },
  amountNegative: {
    color: palette.danger,
    fontWeight: '800',
    fontSize: 20,
  },
  detailLabel: {
    color: palette.textMuted,
    fontWeight: '700',
  },
  experimentalCard: {
    backgroundColor: '#101C30',
    borderColor: '#23314D',
  },
  experimentalTitle: {
    color: palette.white,
    fontWeight: '800',
    fontSize: 18,
  },
  experimentalBody: {
    color: 'rgba(255,255,255,0.84)',
    lineHeight: 21,
  },
});
